# Generated by Django 3.0.6 on 2020-10-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfil', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('imagem_perfil', models.ImageField(upload_to='', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('postado', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comentario', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField()),
                ('comentario_publicado', models.BooleanField()),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Postagem')),
            ],
        ),
    ]
