# Generated by Django 3.0.6 on 2020-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
