# Generated by Django 2.2.12 on 2020-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email_perfil',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
