# Generated by Django 2.2.12 on 2020-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20201022_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='Nenhuma Imagem', null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
