# Generated by Django 2.2.12 on 2020-12-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20201213_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
