# Generated by Django 2.2.12 on 2020-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20201213_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
